CREATE DATABASE partSubmission;


CREATE TABLE IF NOT EXISTS partSubmission.`3D Print` 



CREATE TABLE IF NOT EXISTS partSubmission.`Auxiliary Systems`



CREATE TABLE IF NOT EXISTS partSubmission.Bumpers



CREATE TABLE IF NOT EXISTS partSubmission.Drivetrain



CREATE TABLE IF NOT EXISTS partSubmission.Elevator



CREATE TABLE IF NOT EXISTS partSubmission.Forebar



CREATE TABLE IF NOT EXISTS partSubmission.Intake